BACKLIGHT_ENABLE  = no
BOOTMAGIC_ENABLE  = no
COMMAND_ENABLE    = no
MOUSEKEY_ENABLE   = no
SLEEP_LED_ENABLE  = no
VISUALIZER_ENABLE = no

DYNAMIC_MACRO_ENABLE = yes
LEADER_ENABLE        = yes
TAP_DANCE_ENABLE     = yes
