#define SPLIT_LAYER_STATE_ENABLE

#define RGB_MATRIX_DEFAULT_ON true
// #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_DEFAULT_HUE 150
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_TIMEOUT 5 * 60 * 1000
