#ifndef HOTDOX_ORA_CONFIG_H
#define HOTDOX_ORA_CONFIG_H

#define DYNAMIC_MACRO_USER_CALL
#define DYNAMIC_MACRO_NO_NESTING

#define PERMISSIVE_HOLD

#define TAPPING_TERM 200
#define TAPPING_TOGGLE 1

#define LEADER_TIMEOUT 750
#define LEADER_PER_KEY_TIMING

#endif // HOTDOX_ORA_CONFIG_H
