#pragma once

#define DYNAMIC_MACRO_USER_CALL
#define DYNAMIC_MACRO_NO_NESTING

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#ifdef TAPPING_TERM
#undef TAPPING_TERM
#endif
#define TAPPING_TERM 400
#define TAPPING_TOGGLE 1

#define LEADER_TIMEOUT 750
#define LEADER_PER_KEY_TIMING
