#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define COMBO_SHOULD_TRIGGER

#define DYNAMIC_MACRO_USER_CALL
#define DYNAMIC_MACRO_NO_NESTING

#define PERMISSIVE_HOLD

#ifdef TAPPING_TERM
#undef TAPPING_TERM
#endif
#define TAPPING_TERM 400
#define TAPPING_TOGGLE 1

#define LEADER_TIMEOUT 400
#define LEADER_PER_KEY_TIMING
