#pragma once

#ifdef TAPPING_TERM
#undef TAPPING_TERM
#endif

#define TAPPING_TERM 200
#define FLOW_TAP_TERM 150
#define LEADER_TIMEOUT 200

#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define TAPPING_TOGGLE 1
#define LEADER_PER_KEY_TIMING
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define COMBO_SHOULD_TRIGGER

#define DYNAMIC_MACRO_USER_ALL
#define DYNAMIC_MACRO_NO_NESTING
