BOOTMAGIC_ENABLE     = yes
CAPS_WORD_ENABLE     = yes
COMBO_ENABLE         = yes
DYNAMIC_MACRO_ENABLE = yes
KEY_LOCK_ENABLE      = yes
LEADER_ENABLE        = yes
TAP_DANCE_ENABLE     = yes

COMMAND_ENABLE       = no
CONSOLE_ENABLE       = no
GRAVE_ESC_ENABLE     = no
KEY_LOCK_ENABLE      = no
MAGIC_ENABLE         = no
MOUSEKEY_ENABLE      = no
OS_DETECTION_ENABLE  = no
SPACE_CADET_ENABLE   = no
